### ISSUE TITLE
Style tweaks

### ISSUE THREAD

**Issue by rossettistone** [rossettistone/bizport#150]
- [x] ~~Fix expand/collapse arrow on Launch section (only?) when expanded~~
- [x] ~~Ensure both physical location options fill full height when translated to Spanish~~(moved to #177)
- [x] ~~Header Bar sizing: App bar height: 56dp App bar left and right padding: 16dp App bar icon top, bottom, left padding: 16dp App bar title bottom padding: 20dp https://material.google.com/layout/structure.html#structure-app-bar.~~ (tracked in #179)
- [x] ~~Change "Launch" to "Grow"~~ (tracked in #178)
- [x] Desktop version section headers "Plan, Apply, Grow" look button like but they don't have any interaction associated. So remove drop shadow and corner radius.

**Comment by rossettistone** [comment]
@lisaratner Is "Move Menu icon to far left" still accurate? From what I see in the Opportunity Matching designs, we're still counting on the menu button being on the right.

**Comment by lisaratner** [comment]
@rossettistone Hey! I removed "move menu icon to far left", let's keep it on the right since we need the left for the back button. Thanks!
