### ISSUE TITLE
My Checklist Page

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#59]
Add to menu

**Comment by rossettistone** [comment]
Steps:
- [ ] Create `checklist_item` model
- [ ] Write seeds file with all checklist items as `checklist_items`
- [ ] Refactor views to contain `checklist_items` from DB
- [ ] Create index view of `checklist_items`
